[VisualStudio]
# Visual Studio 安装路径
# 例如: C:\Program Files\Microsoft Visual Studio\18\Community
VS_INSTALL_DIR=C:\Program Files\Microsoft Visual Studio\18\Community

[vcpkg]
# vcpkg 目录路径（支持绝对路径，或相对此文件的相对路径）
# 例如: ..\..\vcpkg  或  D:\dev\vcpkg
VCPKG_DIR=D:\file_mx\aaaaa\learn-media\vcpkg
